### ISSUE TITLE
Clarify purpose of hit counter and webring

### ISSUE THREAD

**Issue by crcastle** [fostive/wickedcoolkit.com#70]
I have heard confusion from one or maybe two people about where they should paste in the hit counter and webring code. The descriptions for them on wickedcoolkit.com say "your site", but it's not clear if "your site" is your trading card heroku app or a personal site.

<img width="790" alt="CleanShot 2021-02-05 at 16 12 36@2x" src="https://user-images.githubusercontent.com/275734/107090694-970bf800-67ce-11eb-9c3b-2e719f50eaef.png">

This might be related to people not remembering hit counters or webrings from the 90s / early 2000s. Should there be a link from each of these descriptions to an FAQ page with [this content](https://docs.google.com/document/d/1ALkNt2W3qk-AzGmW-_r45YN4YBxLISBEN5YXRJyK-QM/edit)?

**Comment by lynnandtonic** [comment]
@crcastle Ah ok! I’ll update that text to make it more clear and get the FAQ page going.

**Comment by lynnandtonic** [comment]
@crcastle PR for you here: https://github.com/fostive/wickedcoolkit.com/pull/71
